---
# Source: juice-shop/templates/service.yaml
# SPDX-FileCopyrightText: 2020 iteratec GmbH
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: my-juice-shop
  labels:
    helm.sh/chart: juice-shop-2.9.1
    app.kubernetes.io/name: juice-shop
    app.kubernetes.io/instance: my-juice-shop
    app.kubernetes.io/version: "v12.7.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: juice-shop
    app.kubernetes.io/instance: my-juice-shop
---
# Source: juice-shop/templates/deployment.yaml
# SPDX-FileCopyrightText: 2020 iteratec GmbH
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-juice-shop
  labels:
    helm.sh/chart: juice-shop-2.9.1
    app.kubernetes.io/name: juice-shop
    app.kubernetes.io/instance: my-juice-shop
    app.kubernetes.io/version: "v12.7.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    {}
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: juice-shop
      app.kubernetes.io/instance: my-juice-shop
  template:
    metadata:
      labels:
        app.kubernetes.io/name: juice-shop
        app.kubernetes.io/instance: my-juice-shop
      annotations:
        {}
    spec:
      securityContext:
        {}
      containers:
        - name: juice-shop
          securityContext:
            {}
          image: "docker.io/bkimminich/juice-shop:v12.7.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
---
# Source: juice-shop/templates/ingress.yaml
# SPDX-FileCopyrightText: 2020 iteratec GmbH
#
# SPDX-License-Identifier: Apache-2.0
---
# Source: juice-shop/templates/tests/test-connection.yaml
# SPDX-FileCopyrightText: 2020 iteratec GmbH
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Pod
metadata:
  name: "my-juice-shop-test-connection"
  labels:

    helm.sh/chart: juice-shop-2.9.1
    app.kubernetes.io/name: juice-shop
    app.kubernetes.io/instance: my-juice-shop
    app.kubernetes.io/version: "v12.7.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args:  ['my-juice-shop:3000']
  restartPolicy: Never
